# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - deploy-gitactions
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Estoy ejecuntado el Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: integration
    concurrency: deploy-gropup
    steps:
      - name: Estoy ejecuntado el Checkout
        uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_PRACTICA_TOKEN }}
